config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers,skip: [:passwords], controllres: {
  #   registration: "public/registration",
  #   sessions: 'public/sessions'
  # devise_for :customers,skip: [:passwords, :registrations] 
  # as :customer do 
  #     get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
  #     post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  #   end 
  
  
   # devise_for :admins, skip: [:registrations, :passwords], controllres: {
  #   #registration: "admin/registration",
  #   sessions: "admin/sessions"
  # }
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  
  scope module: :public do
    devise_for :customers,skip: [:passwords, :registrations] 
      as :customer do 
      get 'customers/sign_up', to: 'registrations#new', as: :new_customer_registration
      post 'customers/sign_up', to: 'registrations#create', as: :customer_registration
    end 
    get 'homes/top' => 'homes#top', as: 'top' 
    get 'homes/about' => 'homes#about', as: 'about'  #public_about_path
    resources :items,        :only => [:index, :show]
    get 'customers/exit' => 'customers#exit', as: 'exit'
    patch 'customers/period' => 'customers#period', as: 'period'
    resources :customers,    :only => [:show, :edit, :update]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all' #destroy_all_path
    resources :cart_items,   :only => [:index, :update, :create, :destroy]
    post 'orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get 'orders/completion' => 'orders#completion', as: 'completion'
    resources :orders,        :only => [:new, :index, :show, :create]
    resources :addresses,   :except => [:new, :show]
    
  end
  
 
  
  namespace :admin do
    resources :genres,    :only => [:index, :create, :edit, :update]
    resources :customers, :only => [:index, :show, :edit, :update]
    resources :orders,     :only => [:show, :update]
    resources :order_details, :only => [:update]
    resources :items,     :except => [:destroy]
    get 'homes/top' => 'homes#top', as: 'top' 
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  def with_tax_price
    (price_without_tax * 1.1).floor
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image.variant(resize_to_limit: [width, height]).processed
  end
  


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  layout 'admin'
  before_action :move_to_signed_in
  
  def index
    @item = Item.page(params[:page])
    
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_items_path
  end
  
  def show
   @item = Item.find(params[:id])
  end
  
  def edit
   @item = Item.find(params[:id])
  end
  
  def update 
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
private


  def item_params
    params.require(:item).permit(:name, :explanation, :price_without_tax, :item_status, :image, :genre_id)
  end
  
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end
 

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item,url: admin_item_path(@item.id) do |f| %>
<p>商品画像</p>
<%= f.file_field :image, accept:"image/*" %>

<p>商品名</p>
<%= f.text_field :name %>

<p>商品説明</p>
<%= f.text_area :explanation %>

<p>ジャンル</p>
<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>

<p>税抜価格</p>
<%= f.number_field :price_without_tax %>
<p>円</p>
<!--こことステータスが分からない-->

<p>販売ステータス</p>
<%= f.radio_button :item_status, "true" %>
<%= f.label :item_status, "販売中" %>

<%= f.radio_button :item_status, "false" %>
<%= f.label :item_status, "販売停止中" %>

<%= f.submit '変更を保存' %>

<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>

<%= link_to new_admin_item_path,class: 'btn btn-outline-secondary btn-block' do %>
<i class="fas fa-plus-circle"></i>
<% end %>

<% @item.each do |item| %>
<p>商品ID</p>
<span>
  <%= link_to item.id, admin_item_path(item.id) %>
</span> 

<p>商品名</p>
<span><%= item.name %></span>

<p>税抜価格</p>
<span><%= item.price_without_tax %></span>

<p>ジャンル</p>
<span><%= item.genre.name %></span>

<p>ステータス</p>
<span>
  <% if item.item_status? %>
  <p>販売中</p>
  <% else %>
  <p>販売停止中</p>
  <% end %>
</span> 
<% end %>

<%= paginate @item %>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item,url: admin_items_path do |f| %>
<p>商品画像</p>
<%= f.file_field :image, accept:"image/*" %>

<p>商品名</p>
<%= f.text_field :name %>

<p>商品説明</p>
<%= f.text_area :explanation %>

<p>ジャンル</p>
<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>

<p>税抜価格</p>
<%= f.number_field :price_without_tax %>
<p>円</p>
<!--こことステータスが分からない-->

<p>販売ステータス</p>
<%= f.radio_button :item_status, "true" %>
<%= f.label :item_status, "販売中" %>

<%= f.radio_button :item_status, "false" %>
<%= f.label :item_status, "販売停止中" %>

<%= f.submit '新規登録' %>

<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<%= image_tag @item.get_image(100,100) %>

<p>商品名</p>
<span><%= @item.name %></span>

<p>商品説明</p>
<span><%= @item.explanation %></span>

<p>ジャンル</p>
<%= @item.genre.name %>

<p>税込価格</p>

<%= @item.with_tax_price %> (<%= @item.price_without_tax %>) 
円

<p>販売ステータス</p>
<span>
  <% if @item.item_status? %>
  <p>販売中</p>
  <% else %>
  <p>販売停止中</p>
  <% end %>
</span>

<%= link_to "編集する", edit_admin_item_path(@item.id) %>