config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers,skip: [:passwords], controllres: {
  #   registration: "public/registration",
  #   sessions: 'public/sessions'
  # devise_for :customers,skip: [:passwords, :registrations] 
  # as :customer do 
  #     get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
  #     post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  #   end 
  
  
   # devise_for :admins, skip: [:registrations, :passwords], controllres: {
  #   #registration: "admin/registration",
  #   sessions: "admin/sessions"
  # }
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  
  scope module: :public do
    devise_for :customers,skip: [:passwords, :registrations] 
      as :customer do 
      get 'customers/sign_up', to: 'registrations#new', as: :new_customer_registration
      post 'customers/sign_up', to: 'registrations#create', as: :customer_registration
    end 
    get 'homes/top' => 'homes#top', as: 'top' 
    get 'homes/about' => 'homes#about', as: 'about'  #public_about_path
    resources :items,        :only => [:index, :show]
    get 'customers/exit' => 'customers#exit', as: 'exit'
    patch 'customers/period' => 'customers#period', as: 'period'
    resources :customers,    :only => [:show, :edit, :update]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all' #destroy_all_path
    resources :cart_items,   :only => [:index, :update, :create, :destroy]
    post 'orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get 'orders/completion' => 'orders#completion', as: 'completion'
    resources :orders,        :only => [:new, :index, :show, :create]
    resources :addresses,   :except => [:new, :show]
    
  end
  
 
  
  namespace :admin do
    resources :genres,    :only => [:index, :create, :edit, :update]
    resources :customers, :only => [:index, :show, :edit, :update]
    resources :orders,     :only => [:show, :update]
    resources :order_details, :only => [:update]
    resources :items,     :except => [:destroy]
    get 'homes/top' => 'homes#top', as: 'top' 
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items 
  has_many :orders
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  layout 'admin' 
  before_action :move_to_signed_in
  
  
  def index
    @customer = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end
  
  private
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name,  :last_name_kana, 
                                     :first_name_kana,:postal_code, :address, :telephone_number)
  end
  
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer,url: admin_customer_path(@customer.id) do |f| %>
<h2>
<%= @customer.first_name %> <%= @customer.last_name %>
さんの<strong>会員情報編集</strong></h2>

<p>会員ID</p>
<%= @customer.id %>
<p>氏名</p>
<%= f.text_field :last_name %>
<%= f.text_field :first_name %>

<p>フリガナ</p>
<%= f.text_field :last_name_kana %>
<%= f.text_field :first_name_kana %>

<p>郵便番号</p>
<%= f.text_field :postal_code %>

<p>住所</p>
<%= f.text_field :address %>

<p>電話番号</p>
<%= f.text_field :telephone_number %>

<p>メールアドレス</p>
<%= f.text_field :email %>

<p>会員ステータス</p>
<%= f.radio_button :is_deleted, "true" %>
<%= f.label :is_deleted, "有効" %>

<%= f.radio_button :is_deleted, "false" %>
<%= f.label :is_deleted, "退会" %>

<%= f.submit '変更を保存' %>

<% end %>

app/views/admin/customers/index.html.erb
<h2>会員</h2>
<% @customer.each do |customer| %>
<p>会員ID</p>
<span>
  <%= customer.id%>
</span> 

<p>氏名</p>
<span><%= link_to customer.last_name, admin_customer_path(customer.id) %></span>
<span><%= link_to customer.first_name, admin_customer_path(customer.id) %></span>

<p>メールアドレス</p>
<span><%= customer.email %></span>

<p>ステータス</p>
<span>
  <% if customer.is_deleted? %>
  <p>有効</p>
  <% else %>
  <p>退会</p>
  <% end %>
</span> 
<% end %>

<%= paginate @customer %>

app/views/admin/customers/show.html.erb
<h2>
<%= @customer.first_name%> <%= @customer.last_name %>
さんの<strong>会員詳細</strong></h2>

<p>会員ID</p>
<%= @customer.id %>

<p>氏名</p>
<%= @customer.last_name %>
<%= @customer.first_name %>
<p>フリガナ</p>
<%= @customer.last_name_kana %>
<%= @customer.first_name_kana %>

<p>郵便番号</p>
<%= @customer.postal_code %>
<p>住所</p>
<%= @customer.address %>
<p>電話番号</p>
<%= @customer.telephone_number %>
<p>メールアドレス</p>
<%= @customer.email %>
<p>会員ステータス</p>
<span>
  <% if @customer.is_deleted? %>
  <p>有効</p>
  <% else %>
  <p>退会</p>
  <% end %>
</span>
<%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
<%= link_to "注文履歴一覧を見る", admin_top_path %>