config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers,skip: [:passwords], controllres: {
  #   registration: "public/registration",
  #   sessions: 'public/sessions'
  # devise_for :customers,skip: [:passwords, :registrations] 
  # as :customer do 
  #     get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
  #     post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  #   end 
  
  
   # devise_for :admins, skip: [:registrations, :passwords], controllres: {
  #   #registration: "admin/registration",
  #   sessions: "admin/sessions"
  # }
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  
  scope module: :public do
    devise_for :customers,skip: [:passwords, :registrations] 
      as :customer do 
      get 'customers/sign_up', to: 'registrations#new', as: :new_customer_registration
      post 'customers/sign_up', to: 'registrations#create', as: :customer_registration
    end 
    get 'homes/top' => 'homes#top', as: 'top' 
    get 'homes/about' => 'homes#about', as: 'about'  #public_about_path
    resources :items,        :only => [:index, :show]
    get 'customers/exit' => 'customers#exit', as: 'exit'
    patch 'customers/period' => 'customers#period', as: 'period'
    resources :customers,    :only => [:show, :edit, :update]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all' #destroy_all_path
    resources :cart_items,   :only => [:index, :update, :create, :destroy]
    post 'orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get 'orders/completion' => 'orders#completion', as: 'completion'
    resources :orders,        :only => [:new, :index, :show, :create]
    resources :addresses,   :except => [:new, :show]
    
  end
  
 
  
  namespace :admin do
    resources :genres,    :only => [:index, :create, :edit, :update]
    resources :customers, :only => [:index, :show, :edit, :update]
    resources :orders,     :only => [:show, :update]
    resources :order_details, :only => [:update]
    resources :items,     :except => [:destroy]
    get 'homes/top' => 'homes#top', as: 'top' 
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + customer.last_name + customer.first_name
end


  
  enum payment_method: { credit_card:0, transfer:1 }
  enum order_status: { waiting_for_payment:0, payment_confirmation:1, production:2, shipping_preparation:3, sent:4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout 'admin'
   before_action :move_to_signed_in
  
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)
  end
  
  private
  
  def order_params
     params.require(:order).permit(:order_status)
  end
  
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end
 
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<p><strong>購入者</strong></p>
<%= @order.name %>

<p><strong>注文日</strong></p>
<%= @order.created_at %>

<p><strong>配送先</strong></p>
<%= @order.address %>

<p><strong>支払方法</strong></p>
<%= @order.payment_method_i18n %>

<p><strong>注文ステータス</strong></p>
<%= form_with model: @order, url: admin_order_path(@order.id) do |order| %>
<%= order.select :order_status, Order.order_statuses_i18n.invert %>
<!--Order.order_statuses_i18n.invert-->
<!-- => {"入金待ち"=>"waiting_for_payment", "入金確認"=>"payment_confirmation", " 製作中"=>"production", "発送準備中"=>"shipping_preparation", "発送済み"=>"sent"} -->

<%= order.submit '更新' %>
<% end %>

<% @order.order_details.each do |order_detail| %>
<p><strong>商品名</strong></p>
<%= order_detail.item.name %>

<p><strong>単価（税込）</strong></p>
<%= order_detail.purchase_price %>

<p><strong>数量</strong></p>
<%= order_detail.quantity %>

<p><strong>小計</strong></p>
<%= (order_detail.purchase_price * order_detail.quantity) %>
<%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
<p><strong>制作ステータス</strong></p>
<%= f.select :makeing_status, OrderDetail.makeing_statuses_i18n.invert %>

<%= f.submit '更新' %>

<% end %>
<% end %>

<p><strong>商品合計</strong></p>
<% @total = 0 %>
<% @order.order_details.each do |order_detail| %>
<% @total = @total + (order_detail.quantity * order_detail.with_tax_price) %>
<% end %>
<%= @total %>

<p><strong>送料</strong></p>
<% @postage = 800 %>
<%= @postage %>

<p><strong>請求金額合計</strong></p>
<%= @postage + @total %>