config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers,skip: [:passwords], controllres: {
  #   registration: "public/registration",
  #   sessions: 'public/sessions'
  # devise_for :customers,skip: [:passwords, :registrations] 
  # as :customer do 
  #     get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
  #     post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  #   end 
  
  
   # devise_for :admins, skip: [:registrations, :passwords], controllres: {
  #   #registration: "admin/registration",
  #   sessions: "admin/sessions"
  # }
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  
  scope module: :public do
    devise_for :customers,skip: [:passwords, :registrations] 
      as :customer do 
      get 'customers/sign_up', to: 'registrations#new', as: :new_customer_registration
      post 'customers/sign_up', to: 'registrations#create', as: :customer_registration
    end 
    get 'homes/top' => 'homes#top', as: 'top' 
    get 'homes/about' => 'homes#about', as: 'about'  #public_about_path
    resources :items,        :only => [:index, :show]
    get 'customers/exit' => 'customers#exit', as: 'exit'
    patch 'customers/period' => 'customers#period', as: 'period'
    resources :customers,    :only => [:show, :edit, :update]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all' #destroy_all_path
    resources :cart_items,   :only => [:index, :update, :create, :destroy]
    post 'orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get 'orders/completion' => 'orders#completion', as: 'completion'
    resources :orders,        :only => [:new, :index, :show, :create]
    resources :addresses,   :except => [:new, :show]
    
  end
  
 
  
  namespace :admin do
    resources :genres,    :only => [:index, :create, :edit, :update]
    resources :customers, :only => [:index, :show, :edit, :update]
    resources :orders,     :only => [:show, :update]
    resources :order_details, :only => [:update]
    resources :items,     :except => [:destroy]
    get 'homes/top' => 'homes#top', as: 'top' 
  
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def sub_total
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, dependent: :destroy
  has_many :cart_items 
  has_many :orders
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  def with_tax_price
    (price_without_tax * 1.1).floor
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image.variant(resize_to_limit: [width, height]).processed
  end
  


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + customer.last_name + customer.first_name
end


  
  enum payment_method: { credit_card:0, transfer:1 }
  enum order_status: { waiting_for_payment:0, payment_confirmation:1, production:2, shipping_preparation:3, sent:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item 
  belongs_to :order
  enum makeing_status: { production_not_allowed: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3}
  
  def sub_total
   purchase_price * quantity
  end
  
  def with_tax_price
   (self.purchase_price * 1.1).round
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  layout 'admin'
  before_action :move_to_signed_in
  
  def index
    @genre = Genre.new
    @genres = Genre.all
    
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private

  def genre_params
     params.require(:genre).permit(:name)
  end
  
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout 'admin'
  before_action :move_to_signed_in
  
  def top
    @orders = Order.page(params[:page])
  end
  
private
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  layout 'admin'
  before_action :move_to_signed_in
  
  def index
    @item = Item.page(params[:page])
    
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_items_path
  end
  
  def show
   @item = Item.find(params[:id])
  end
  
  def edit
   @item = Item.find(params[:id])
  end
  
  def update 
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
private


  def item_params
    params.require(:item).permit(:name, :explanation, :price_without_tax, :item_status, :image, :genre_id)
  end
  
  def move_to_signed_in
    unless admin_signed_in?
    redirect_to  admin_session_path

    end
  end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<h2>会員登録がお済みでない方</h2>
  <%= link_to "こちら", new_session_path(resource_name) %><p>から新規登録を行ってください。</p><br />
  
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>長野ケーキ屋</h1>
     <% if admin_signed_in? %>
      <li>
        <%= link_to "商品一覧" ,admin_items_path %>
      </li>
      
      <li>
        <%= link_to "会員一覧" ,admin_customers_path %>
      </li>
      
      <li>
        <%= link_to "注文履歴一覧" ,admin_top_path %>
      </li>
      
       <li>
        <%= link_to "ジャンル一覧" ,admin_genres_path %>
      </li>
      
      <li>
        <%= link_to "ログアウト" ,destroy_admin_session_path, method: :delete %>
      </li>
      
     <% else %>
      <li>
        <%= link_to "About" ,about_path %>
      </li>
      
      <li>
        <%= link_to "商品一覧" ,items_path %>
      </li>
      
      <li>
        <%= link_to "新規登録" ,new_customer_registration_path %>
      </li>
      
      <li>
        <%= link_to "ログイン" ,customer_session_path %>
      </li>
    <% end %>
    </header>
    
    
    
    <%= yield %>
    <footer>
      
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <nav class="navbar navbar-auto bg-light">
          <span class="navbar-right mb-0 h1">
            長野ケーキ屋
          </span>
        </nav>

    
     <% if customer_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <p>ようこそ、 <%= current_customer.last_name %>さん!</p>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ" ,customer_path(current_customer.id) %>
            </li>
            
            <li class="nav-item">
              <%= link_to "商品一覧" ,items_path %>
            </li>
            
            <li class="nav-item">
              <%= link_to "カート" ,cart_items_path %>
            </li>
            
            <li class="nav-item">
              <%= link_to "ログアウト" ,destroy_customer_session_path, method: :delete %>
            </li>
             
          <% else %>
          
            <li class="nav-item">
              <%= link_to "About" ,about_path %>
            </li>
            
            <li class="nav-item">
              <%= link_to "商品一覧" ,items_path %>
            </li>
              
            <li class="nav-item">
              <%= link_to "新規登録" ,new_customer_registration_path %>
            </li>
            
            <li class="nav-item">
              <%= link_to "ログイン" ,customer_session_path %>
            </li>
            <% end %>
            </li>
          </ul>　
        </li>
      </ul>
      </div>
        
    </header>
    
    
    
    <%= yield %>
    <footer>
      
    </footer>
  </body>
  
</html>